### ISSUE TITLE
Drop database link statement fails when adding a new target

### ISSUE THREAD

**Issue by johnnyq72** [pioro/orasash#13]
With 2.4 I ran into this issue, and I don't know if it's me or if it's something in the software.
When adding a database to the repository, SASH_REPO gave an issue:

This is what the procedure did:

SQL> @adddb
##################################################################################################
For non multitenant databases use unique database name and instance name
For multitenant - use PDB name as database name and CDB name as a instance name
##################################################################################################

Enter database name db.domain
Enter number of instances [default 1]
Enter host name for instance number 1 host.domain
Enter instance name (or CDB for 12c) for instance number 1 [ default db.domain ] db
Enter listener port number [default 1521]
Enter SASH password on target database sash
BEGIN sash_repo.add_db(' plsorastage2.portrix.net', 1521, 'sash', 'plsora02.portrix.net', 'plsora02',1, null); END;

*
ERROR at line 1:
ORA-00933: SQL command not properly ended
ORA-06512: at "PORTRIXASH.SASH_REPO", line 365
ORA-06512: at line 1

This is the hack:
(commenting out the line for 'drop database' which was not yet required)

    begin
  --      execute immediate 'drop database link ' || v_dblink;
        dbms_output.put_line('Link dropped');
    exception when no_db_link then
            log_message('add_db', 'no db link - moving forward ' || v_dblink  ,'W');
    end;

This is what the procedure now does:

SQL> @adddb
##################################################################################################
For non multitenant databases use unique database name and instance name
For multitenant - use PDB name as database name and CDB name as a instance name
##################################################################################################

Enter database name db.domain
Enter number of instances [default 1]
Enter host name for instance number 1 host.domain
Enter instance name (or CDB for 12c) for instance number 1 [ default db.domain ] db
Enter listener port number [default 1521]
Enter SASH password on target database sash
BEGIN sash_repo.start_collecting_jobs; END;

*
ERROR at line 1:
ORA-20037: SASH  start_collecting_jobs error ORA-20036: SASH  start_collecting_jobs error ORA-27478: job "PORTRIXASH.SASH_PKG_COLLECT_1_965977554" is running
ORA-06512: at "PORTRIXASH.SASH_REPO", line 313
ORA-06512: at line 1

##################################################################################################
Database added.
##################################################################################################

Possibly the last message is nothing significant because it already reports that the collecting jobs are running. This is also verified:

SQL> @job_stat

JOB_NAME                       LAST_START_DATE                     NEXT_RUN_DATE                       STATE           FAILURE_COUNT
------------------------------ ----------------------------------- ----------------------------------- --------------- -------------
SASH_PKG_COLLECT_1_965977554   27-MAR-15 01.00.34.256487 PM +00:00 27-MAR-15 01.00.34.000000 PM +00:00 RUNNING                     0
SASH_PKG_GET_ALL_1_965977554   27-MAR-15 01.01.29.733804 PM +00:00 27-MAR-15 01.15.00.000000 PM +00:00 SCHEDULED                   0
SASH_REPO_PURGE                                                    28-MAR-15 12.00.00.000000 AM +00:00 SCHEDULED                   0
SASH_REPO_WATCHDOG             27-MAR-15 01.00.34.284346 PM +00:00 27-MAR-15 01.05.34.000000 PM +00:00 SCHEDULED                   0

I have not further investigated the start_collection_jobs-issue, since they are running :-)
Furthermore I still need to figure out the correct syntax for the "drop dblink" line.

**Comment by pioro** [comment]
Hi,

I think a problem happen because you put a space before a host name

BEGIN sash_repo.add_db(' plsorastage2.portrix.net', 1521, 'sash', 'plsora02.portrix.net', 'plsora02',1, null); END;

Here is a host from your example - ' plsorastage2.portrix.net'
Host name is used a part of DB link and this a DB link name which has been generated
'plsora02.portrix.net_ plsorast' - as you can see there is a space in the name.

I have to review code and add a rule to delete space character from name.
I will update issue when I fix this.

Marcin

**Comment by johnnyq72** [comment]
Hi Marcin,

Ah, okay, that was stupid of course. Bizarre that this happened 
identically like n times over, where n > 15
Thanks for the fix, though!!

Cheers,

Jan Karremans
Oracle ACE Associate
JK-Consult

MOB: +31 6 16 38 96 07
E: j.karremans@jk-consult.nl <mailto:j.karremans@jk-consult.nl>
Skype: jankarremansnl
Blog: www.jk-consult.nl <http://www.jk-consult.nl/>

The information contained in this e-mail, including possible 
attachments, is confidential and is solely for the use of the intended 
recipient(s). Should you have received this e-mail unintentionally you 
are then requested to inform the sender and to destroy the message. It 
is prohibited to use or disclose the information this message contains 
in whatsoever way.

Marcin Przepiorowski schreef op 03-05-15 om 21:21:

**Comment by pioro** [comment]
Hi Jan,
Fix pushed to sash_dev - you can pull changes if you want to test it.
Closing this issue.

Marcin
